services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radiant-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - radiant-network

networks:
  radiant-network:
    name: radiant-network
    driver: bridge
